name: CI

on:
  push:

jobs:
  build:
    name: Build and Pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Restore
        run: dotnet restore solution.sln
      - name: Build
        run: dotnet build solution.sln --configuration Release --no-restore
      - name: Pack NuGet
        run: dotnet pack src/nperf/nperf.csproj --configuration Release --output artifacts/nuget --no-build --no-restore
      - name: Upload NuGet Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: artifacts/nuget
